### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by xloem** [vadimkantorov/pydlpack#1]
Hi,

What license is your code shared under?  Would you be willing to consider GPL-3?

Alternatively, specifying any license at all will help people be able to work off your code, reuse it, and make contributions back.  They can judge whether doing the work will meet their intended uses.  Without a license, one can't know what the future holds.

**Comment by vadimkantorov** [comment]
I added a note for MIT license. While reusing the code, mind that recent actual dlpack headers might change and the bindings may need some updates.

**Comment by xloem** [comment]
Thanks a bunch.
